# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cubetimer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(1119, 793)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        TabWidget.setFont(font)
        TabWidget.setAutoFillBackground(False)
        TabWidget.setStyleSheet(_fromUtf8("background-color: rgb(33, 33, 33);"))
        self.tab_timer = QtGui.QWidget()
        self.tab_timer.setObjectName(_fromUtf8("tab_timer"))
        self.tW_stats1 = QtGui.QTableWidget(self.tab_timer)
        self.tW_stats1.setGeometry(QtCore.QRect(20, 510, 350, 200))
        self.tW_stats1.setMaximumSize(QtCore.QSize(350, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tW_stats1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_stats1.setFont(font)
        self.tW_stats1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_stats1.setAutoFillBackground(False)
        self.tW_stats1.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 15pt \"Sawasdee\";"))
        self.tW_stats1.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_stats1.setFrameShadow(QtGui.QFrame.Plain)
        self.tW_stats1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_stats1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_stats1.setAutoScroll(False)
        self.tW_stats1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_stats1.setShowGrid(False)
        self.tW_stats1.setGridStyle(QtCore.Qt.SolidLine)
        self.tW_stats1.setCornerButtonEnabled(False)
        self.tW_stats1.setObjectName(_fromUtf8("tW_stats1"))
        self.tW_stats1.setColumnCount(1)
        self.tW_stats1.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 10, 154))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tW_stats1.setItem(0, 0, item)
        self.tW_stats1.horizontalHeader().setVisible(False)
        self.tW_stats1.horizontalHeader().setDefaultSectionSize(200)
        self.tW_stats1.horizontalHeader().setMinimumSectionSize(200)
        self.tW_stats1.horizontalHeader().setStretchLastSection(True)
        self.tW_stats1.verticalHeader().setDefaultSectionSize(33)
        self.tW_stats1.verticalHeader().setMinimumSectionSize(35)
        self.tW_stats1.verticalHeader().setStretchLastSection(True)
        self.tW_stats2 = QtGui.QTableWidget(self.tab_timer)
        self.tW_stats2.setGeometry(QtCore.QRect(390, 510, 350, 200))
        self.tW_stats2.setMaximumSize(QtCore.QSize(350, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_stats2.setFont(font)
        self.tW_stats2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_stats2.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 15pt \"Sawasdee\";"))
        self.tW_stats2.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_stats2.setAutoScroll(False)
        self.tW_stats2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_stats2.setShowGrid(False)
        self.tW_stats2.setObjectName(_fromUtf8("tW_stats2"))
        self.tW_stats2.setColumnCount(1)
        self.tW_stats2.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setHorizontalHeaderItem(0, item)
        self.tW_stats2.horizontalHeader().setVisible(False)
        self.tW_stats2.horizontalHeader().setDefaultSectionSize(200)
        self.tW_stats2.horizontalHeader().setMinimumSectionSize(200)
        self.tW_stats2.horizontalHeader().setStretchLastSection(True)
        self.tW_stats2.verticalHeader().setDefaultSectionSize(33)
        self.tW_stats2.verticalHeader().setMinimumSectionSize(33)
        self.tW_stats2.verticalHeader().setStretchLastSection(True)
        self.l_chronoTime = QtGui.QLabel(self.tab_timer)
        self.l_chronoTime.setGeometry(QtCore.QRect(180, 200, 797, 204))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(100)
        self.l_chronoTime.setFont(font)
        self.l_chronoTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_chronoTime.setAlignment(QtCore.Qt.AlignCenter)
        self.l_chronoTime.setObjectName(_fromUtf8("l_chronoTime"))
        self.cB_puzzleType = QtGui.QComboBox(self.tab_timer)
        self.cB_puzzleType.setGeometry(QtCore.QRect(20, 28, 70, 31))
        self.cB_puzzleType.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        self.cB_puzzleType.setFont(font)
        self.cB_puzzleType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cB_puzzleType.setObjectName(_fromUtf8("cB_puzzleType"))
        self.cB_puzzleType.addItem(_fromUtf8(""))
        self.pB_timeDelete = QtGui.QPushButton(self.tab_timer)
        self.pB_timeDelete.setGeometry(QtCore.QRect(760, 710, 75, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        self.pB_timeDelete.setFont(font)
        self.pB_timeDelete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pB_timeDelete.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pB_timeDelete.setObjectName(_fromUtf8("pB_timeDelete"))
        self.lV_times = QtGui.QListView(self.tab_timer)
        self.lV_times.setGeometry(QtCore.QRect(764, 510, 331, 191))
        self.lV_times.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(18)
        self.lV_times.setFont(font)
        self.lV_times.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lV_times.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lV_times.setFrameShadow(QtGui.QFrame.Plain)
        self.lV_times.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lV_times.setAutoScroll(True)
        self.lV_times.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lV_times.setAlternatingRowColors(True)
        self.lV_times.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lV_times.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.lV_times.setMovement(QtGui.QListView.Free)
        self.lV_times.setLayoutMode(QtGui.QListView.SinglePass)
        self.lV_times.setViewMode(QtGui.QListView.ListMode)
        self.lV_times.setObjectName(_fromUtf8("lV_times"))
        self.l_scramble = QtGui.QLabel(self.tab_timer)
        self.l_scramble.setGeometry(QtCore.QRect(120, 40, 881, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_scramble.sizePolicy().hasHeightForWidth())
        self.l_scramble.setSizePolicy(sizePolicy)
        self.l_scramble.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(16)
        self.l_scramble.setFont(font)
        self.l_scramble.setAcceptDrops(False)
        self.l_scramble.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_scramble.setTextFormat(QtCore.Qt.PlainText)
        self.l_scramble.setAlignment(QtCore.Qt.AlignCenter)
        self.l_scramble.setWordWrap(True)
        self.l_scramble.setObjectName(_fromUtf8("l_scramble"))
        self.pBar_mean = QtGui.QProgressBar(self.tab_timer)
        self.pBar_mean.setGeometry(QtCore.QRect(260, 400, 281, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pBar_mean.setFont(font)
        self.pBar_mean.setAutoFillBackground(False)
        self.pBar_mean.setStyleSheet(_fromUtf8("QProgressBar { text-align: center; color: #FFFFFF;font:  75 16pt \"Sawasdee\";font-weight:bold;}\n"
"QProgressBar::chunk { background-color: #00FF00; width: 1px; margin: 0.6px;}"))
        self.pBar_mean.setProperty("value", 100)
        self.pBar_mean.setTextVisible(True)
        self.pBar_mean.setOrientation(QtCore.Qt.Horizontal)
        self.pBar_mean.setInvertedAppearance(False)
        self.pBar_mean.setObjectName(_fromUtf8("pBar_mean"))
        self.pBar_overtime = QtGui.QProgressBar(self.tab_timer)
        self.pBar_overtime.setGeometry(QtCore.QRect(540, 400, 281, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pBar_overtime.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pBar_overtime.setFont(font)
        self.pBar_overtime.setAutoFillBackground(False)
        self.pBar_overtime.setStyleSheet(_fromUtf8("QProgressBar { text-align: center; color: #FFFFFF;font:  75 16pt \"Sawasdee\";font-weight:bold;}\n"
"QProgressBar::chunk { background-color: #FF0000; width: 1px; margin: 0.6px;}"))
        self.pBar_overtime.setProperty("value", 100)
        self.pBar_overtime.setTextVisible(True)
        self.pBar_overtime.setOrientation(QtCore.Qt.Horizontal)
        self.pBar_overtime.setInvertedAppearance(False)
        self.pBar_overtime.setObjectName(_fromUtf8("pBar_overtime"))
        TabWidget.addTab(self.tab_timer, _fromUtf8(""))
        self.tab_history = QtGui.QWidget()
        self.tab_history.setObjectName(_fromUtf8("tab_history"))
        self.lV_history = QtGui.QListView(self.tab_history)
        self.lV_history.setGeometry(QtCore.QRect(40, 40, 1000, 180))
        self.lV_history.setMaximumSize(QtCore.QSize(1000, 800))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(12)
        self.lV_history.setFont(font)
        self.lV_history.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lV_history.setFrameShape(QtGui.QFrame.Box)
        self.lV_history.setFrameShadow(QtGui.QFrame.Plain)
        self.lV_history.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lV_history.setAutoScroll(True)
        self.lV_history.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lV_history.setAlternatingRowColors(True)
        self.lV_history.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lV_history.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.lV_history.setMovement(QtGui.QListView.Free)
        self.lV_history.setLayoutMode(QtGui.QListView.SinglePass)
        self.lV_history.setViewMode(QtGui.QListView.ListMode)
        self.lV_history.setObjectName(_fromUtf8("lV_history"))
        TabWidget.addTab(self.tab_history, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        item = self.tW_stats1.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Mean", None))
        item = self.tW_stats1.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Average", None))
        item = self.tW_stats1.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Best Time", None))
        item = self.tW_stats1.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Median", None))
        item = self.tW_stats1.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Worst Time", None))
        item = self.tW_stats1.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Standard Deviation", None))
        __sortingEnabled = self.tW_stats1.isSortingEnabled()
        self.tW_stats1.setSortingEnabled(False)
        self.tW_stats1.setSortingEnabled(__sortingEnabled)
        item = self.tW_stats2.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Mean of 3", None))
        item = self.tW_stats2.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Best Mean of 3", None))
        item = self.tW_stats2.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Average of 5", None))
        item = self.tW_stats2.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Best Average of 5", None))
        item = self.tW_stats2.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Average of 12", None))
        item = self.tW_stats2.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Best Average of 12", None))
        self.l_chronoTime.setText(_translate("TabWidget", "00 : 00 . 000", None))
        self.cB_puzzleType.setItemText(0, _translate("TabWidget", "3x3x3", None))
        self.pB_timeDelete.setText(_translate("TabWidget", "Delete", None))
        self.l_scramble.setText(_translate("TabWidget", "R U\' U D\' D D2 B\' D\' R L\' B2 L2 U D\' F\' R D\' D2 B\' B L B U2 U\' U2 ", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_timer), _translate("TabWidget", "Timer", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_history), _translate("TabWidget", "History", None))

