# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cubetimer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(1119, 793)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        TabWidget.setFont(font)
        TabWidget.setAutoFillBackground(False)
        TabWidget.setStyleSheet(_fromUtf8("background-color: rgb(33, 33, 33);"))
        self.tab_timer = QtGui.QWidget()
        self.tab_timer.setObjectName(_fromUtf8("tab_timer"))
        self.gridLayout = QtGui.QGridLayout(self.tab_timer)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cB_puzzleType = QtGui.QComboBox(self.tab_timer)
        self.cB_puzzleType.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        self.cB_puzzleType.setFont(font)
        self.cB_puzzleType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cB_puzzleType.setObjectName(_fromUtf8("cB_puzzleType"))
        self.cB_puzzleType.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.cB_puzzleType, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_scramble = QtGui.QLabel(self.tab_timer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_scramble.sizePolicy().hasHeightForWidth())
        self.l_scramble.setSizePolicy(sizePolicy)
        self.l_scramble.setMinimumSize(QtCore.QSize(800, 0))
        self.l_scramble.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(16)
        self.l_scramble.setFont(font)
        self.l_scramble.setAcceptDrops(False)
        self.l_scramble.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_scramble.setTextFormat(QtCore.Qt.PlainText)
        self.l_scramble.setAlignment(QtCore.Qt.AlignCenter)
        self.l_scramble.setWordWrap(True)
        self.l_scramble.setObjectName(_fromUtf8("l_scramble"))
        self.horizontalLayout_3.addWidget(self.l_scramble, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.l_chronoTime = QtGui.QLabel(self.tab_timer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.l_chronoTime.sizePolicy().hasHeightForWidth())
        self.l_chronoTime.setSizePolicy(sizePolicy)
        self.l_chronoTime.setMinimumSize(QtCore.QSize(0, 350))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(100)
        self.l_chronoTime.setFont(font)
        self.l_chronoTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l_chronoTime.setAlignment(QtCore.Qt.AlignCenter)
        self.l_chronoTime.setObjectName(_fromUtf8("l_chronoTime"))
        self.gridLayout.addWidget(self.l_chronoTime, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pBar_mean = QtGui.QProgressBar(self.tab_timer)
        self.pBar_mean.setMinimumSize(QtCore.QSize(400, 0))
        self.pBar_mean.setMaximumSize(QtCore.QSize(1000, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pBar_mean.setFont(font)
        self.pBar_mean.setAutoFillBackground(False)
        self.pBar_mean.setStyleSheet(_fromUtf8("QProgressBar { text-align: center; color: #FFFFFF;font:  75 16pt \"Sawasdee\";font-weight:bold;}\n"
"QProgressBar::chunk { background-color: #00FF00; width: 1px; margin: 0.6px;}"))
        self.pBar_mean.setProperty("value", 100)
        self.pBar_mean.setTextVisible(True)
        self.pBar_mean.setOrientation(QtCore.Qt.Horizontal)
        self.pBar_mean.setInvertedAppearance(False)
        self.pBar_mean.setObjectName(_fromUtf8("pBar_mean"))
        self.horizontalLayout_4.addWidget(self.pBar_mean)
        self.pBar_overtime = QtGui.QProgressBar(self.tab_timer)
        self.pBar_overtime.setMinimumSize(QtCore.QSize(400, 0))
        self.pBar_overtime.setMaximumSize(QtCore.QSize(1000, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(33, 33, 33))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pBar_overtime.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pBar_overtime.setFont(font)
        self.pBar_overtime.setAutoFillBackground(False)
        self.pBar_overtime.setStyleSheet(_fromUtf8("QProgressBar { text-align: center; color: #FFFFFF;font:  75 16pt \"Sawasdee\";font-weight:bold;}\n"
"QProgressBar::chunk { background-color: #FF0000; width: 1px; margin: 0.6px;}"))
        self.pBar_overtime.setProperty("value", 100)
        self.pBar_overtime.setTextVisible(True)
        self.pBar_overtime.setOrientation(QtCore.Qt.Horizontal)
        self.pBar_overtime.setInvertedAppearance(False)
        self.pBar_overtime.setObjectName(_fromUtf8("pBar_overtime"))
        self.horizontalLayout_4.addWidget(self.pBar_overtime)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tW_stats1 = QtGui.QTableWidget(self.tab_timer)
        self.tW_stats1.setMaximumSize(QtCore.QSize(350, 200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tW_stats1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_stats1.setFont(font)
        self.tW_stats1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_stats1.setAutoFillBackground(False)
        self.tW_stats1.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 15pt \"Sawasdee\";"))
        self.tW_stats1.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_stats1.setFrameShadow(QtGui.QFrame.Plain)
        self.tW_stats1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_stats1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_stats1.setAutoScroll(False)
        self.tW_stats1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_stats1.setShowGrid(False)
        self.tW_stats1.setGridStyle(QtCore.Qt.SolidLine)
        self.tW_stats1.setCornerButtonEnabled(False)
        self.tW_stats1.setObjectName(_fromUtf8("tW_stats1"))
        self.tW_stats1.setColumnCount(1)
        self.tW_stats1.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 10, 154))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tW_stats1.setItem(0, 0, item)
        self.tW_stats1.horizontalHeader().setVisible(False)
        self.tW_stats1.horizontalHeader().setDefaultSectionSize(200)
        self.tW_stats1.horizontalHeader().setMinimumSectionSize(200)
        self.tW_stats1.horizontalHeader().setStretchLastSection(True)
        self.tW_stats1.verticalHeader().setDefaultSectionSize(33)
        self.tW_stats1.verticalHeader().setMinimumSectionSize(35)
        self.tW_stats1.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tW_stats1, QtCore.Qt.AlignLeft)
        self.tW_stats2 = QtGui.QTableWidget(self.tab_timer)
        self.tW_stats2.setMaximumSize(QtCore.QSize(350, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_stats2.setFont(font)
        self.tW_stats2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_stats2.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 15pt \"Sawasdee\";"))
        self.tW_stats2.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_stats2.setAutoScroll(False)
        self.tW_stats2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_stats2.setShowGrid(False)
        self.tW_stats2.setObjectName(_fromUtf8("tW_stats2"))
        self.tW_stats2.setColumnCount(1)
        self.tW_stats2.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setHorizontalHeaderItem(0, item)
        self.tW_stats2.horizontalHeader().setVisible(False)
        self.tW_stats2.horizontalHeader().setDefaultSectionSize(200)
        self.tW_stats2.horizontalHeader().setMinimumSectionSize(200)
        self.tW_stats2.horizontalHeader().setStretchLastSection(True)
        self.tW_stats2.verticalHeader().setDefaultSectionSize(33)
        self.tW_stats2.verticalHeader().setMinimumSectionSize(33)
        self.tW_stats2.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tW_stats2, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lV_times = QtGui.QListView(self.tab_timer)
        self.lV_times.setMaximumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(18)
        self.lV_times.setFont(font)
        self.lV_times.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lV_times.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lV_times.setFrameShadow(QtGui.QFrame.Plain)
        self.lV_times.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lV_times.setAutoScroll(True)
        self.lV_times.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lV_times.setAlternatingRowColors(True)
        self.lV_times.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lV_times.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.lV_times.setMovement(QtGui.QListView.Free)
        self.lV_times.setLayoutMode(QtGui.QListView.SinglePass)
        self.lV_times.setViewMode(QtGui.QListView.ListMode)
        self.lV_times.setObjectName(_fromUtf8("lV_times"))
        self.verticalLayout_4.addWidget(self.lV_times, QtCore.Qt.AlignRight)
        self.pB_timeDelete = QtGui.QPushButton(self.tab_timer)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        self.pB_timeDelete.setFont(font)
        self.pB_timeDelete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pB_timeDelete.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pB_timeDelete.setObjectName(_fromUtf8("pB_timeDelete"))
        self.verticalLayout_4.addWidget(self.pB_timeDelete, QtCore.Qt.AlignRight)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        TabWidget.addTab(self.tab_timer, _fromUtf8(""))
        self.tab_history = QtGui.QWidget()
        self.tab_history.setObjectName(_fromUtf8("tab_history"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_history)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.tab_history)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1000, 0))
        self.label.setMaximumSize(QtCore.QSize(3000, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(50, 50, 50);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lV_history = QtGui.QListView(self.tab_history)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lV_history.sizePolicy().hasHeightForWidth())
        self.lV_history.setSizePolicy(sizePolicy)
        self.lV_history.setMinimumSize(QtCore.QSize(1000, 0))
        self.lV_history.setMaximumSize(QtCore.QSize(3000, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(12)
        self.lV_history.setFont(font)
        self.lV_history.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lV_history.setFrameShape(QtGui.QFrame.NoFrame)
        self.lV_history.setFrameShadow(QtGui.QFrame.Plain)
        self.lV_history.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lV_history.setAutoScroll(True)
        self.lV_history.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lV_history.setAlternatingRowColors(True)
        self.lV_history.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lV_history.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.lV_history.setMovement(QtGui.QListView.Free)
        self.lV_history.setLayoutMode(QtGui.QListView.SinglePass)
        self.lV_history.setViewMode(QtGui.QListView.ListMode)
        self.lV_history.setObjectName(_fromUtf8("lV_history"))
        self.verticalLayout.addWidget(self.lV_history, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tW_histStats1 = QtGui.QTableWidget(self.tab_history)
        self.tW_histStats1.setMaximumSize(QtCore.QSize(300, 180))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tW_histStats1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_histStats1.setFont(font)
        self.tW_histStats1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_histStats1.setAutoFillBackground(False)
        self.tW_histStats1.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 12pt \"Sawasdee\";"))
        self.tW_histStats1.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_histStats1.setFrameShadow(QtGui.QFrame.Plain)
        self.tW_histStats1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_histStats1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_histStats1.setAutoScroll(False)
        self.tW_histStats1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_histStats1.setShowGrid(False)
        self.tW_histStats1.setGridStyle(QtCore.Qt.SolidLine)
        self.tW_histStats1.setCornerButtonEnabled(False)
        self.tW_histStats1.setObjectName(_fromUtf8("tW_histStats1"))
        self.tW_histStats1.setColumnCount(1)
        self.tW_histStats1.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats1.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats1.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats1.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats1.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 10, 154))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tW_histStats1.setItem(0, 0, item)
        self.tW_histStats1.horizontalHeader().setVisible(False)
        self.tW_histStats1.horizontalHeader().setDefaultSectionSize(200)
        self.tW_histStats1.horizontalHeader().setMinimumSectionSize(200)
        self.tW_histStats1.horizontalHeader().setStretchLastSection(True)
        self.tW_histStats1.verticalHeader().setDefaultSectionSize(30)
        self.tW_histStats1.verticalHeader().setMinimumSectionSize(30)
        self.tW_histStats1.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tW_histStats1, QtCore.Qt.AlignLeft)
        self.tW_histStats2 = QtGui.QTableWidget(self.tab_history)
        self.tW_histStats2.setMaximumSize(QtCore.QSize(300, 180))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tW_histStats2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_histStats2.setFont(font)
        self.tW_histStats2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_histStats2.setAutoFillBackground(False)
        self.tW_histStats2.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 12pt \"Sawasdee\";"))
        self.tW_histStats2.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_histStats2.setFrameShadow(QtGui.QFrame.Plain)
        self.tW_histStats2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_histStats2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_histStats2.setAutoScroll(False)
        self.tW_histStats2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_histStats2.setShowGrid(False)
        self.tW_histStats2.setGridStyle(QtCore.Qt.SolidLine)
        self.tW_histStats2.setCornerButtonEnabled(False)
        self.tW_histStats2.setObjectName(_fromUtf8("tW_histStats2"))
        self.tW_histStats2.setColumnCount(1)
        self.tW_histStats2.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 10, 154))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tW_histStats2.setItem(0, 0, item)
        self.tW_histStats2.horizontalHeader().setVisible(False)
        self.tW_histStats2.horizontalHeader().setDefaultSectionSize(125)
        self.tW_histStats2.horizontalHeader().setHighlightSections(True)
        self.tW_histStats2.horizontalHeader().setMinimumSectionSize(125)
        self.tW_histStats2.horizontalHeader().setSortIndicatorShown(False)
        self.tW_histStats2.horizontalHeader().setStretchLastSection(True)
        self.tW_histStats2.verticalHeader().setVisible(False)
        self.tW_histStats2.verticalHeader().setDefaultSectionSize(30)
        self.tW_histStats2.verticalHeader().setMinimumSectionSize(30)
        self.tW_histStats2.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tW_histStats2, QtCore.Qt.AlignHCenter)
        self.tW_histStats3 = QtGui.QTableWidget(self.tab_history)
        self.tW_histStats3.setMaximumSize(QtCore.QSize(300, 180))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tW_histStats3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_histStats3.setFont(font)
        self.tW_histStats3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_histStats3.setAutoFillBackground(False)
        self.tW_histStats3.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 12pt \"Sawasdee\";"))
        self.tW_histStats3.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_histStats3.setFrameShadow(QtGui.QFrame.Plain)
        self.tW_histStats3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_histStats3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_histStats3.setAutoScroll(False)
        self.tW_histStats3.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_histStats3.setShowGrid(False)
        self.tW_histStats3.setGridStyle(QtCore.Qt.SolidLine)
        self.tW_histStats3.setCornerButtonEnabled(False)
        self.tW_histStats3.setObjectName(_fromUtf8("tW_histStats3"))
        self.tW_histStats3.setColumnCount(1)
        self.tW_histStats3.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats3.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats3.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats3.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats3.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats3.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats3.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_histStats3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 10, 154))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tW_histStats3.setItem(0, 0, item)
        self.tW_histStats3.horizontalHeader().setVisible(False)
        self.tW_histStats3.horizontalHeader().setDefaultSectionSize(125)
        self.tW_histStats3.horizontalHeader().setHighlightSections(True)
        self.tW_histStats3.horizontalHeader().setMinimumSectionSize(125)
        self.tW_histStats3.horizontalHeader().setSortIndicatorShown(False)
        self.tW_histStats3.horizontalHeader().setStretchLastSection(True)
        self.tW_histStats3.verticalHeader().setVisible(False)
        self.tW_histStats3.verticalHeader().setDefaultSectionSize(30)
        self.tW_histStats3.verticalHeader().setMinimumSectionSize(30)
        self.tW_histStats3.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tW_histStats3, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.kplotwidget = KPlotWidget(self.tab_history)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kplotwidget.sizePolicy().hasHeightForWidth())
        self.kplotwidget.setSizePolicy(sizePolicy)
        self.kplotwidget.setStyleSheet(_fromUtf8("font: 9pt \"Sawasdee\";"))
        self.kplotwidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.kplotwidget.setBackgroundColor(QtGui.QColor(33, 33, 33))
        self.kplotwidget.setForegroundColor(QtGui.QColor(255, 255, 255))
        self.kplotwidget.setGridColor(QtGui.QColor(56, 56, 58))
        self.kplotwidget.setProperty("grid", True)
        self.kplotwidget.setProperty("objectToolTip", False)
        self.kplotwidget.setObjectName(_fromUtf8("kplotwidget"))
        self.verticalLayout.addWidget(self.kplotwidget)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.label.raise_()
        self.lV_history.raise_()
        self.tW_histStats2.raise_()
        self.tW_histStats3.raise_()
        self.kplotwidget.raise_()
        self.tW_histStats1.raise_()
        TabWidget.addTab(self.tab_history, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        self.cB_puzzleType.setItemText(0, _translate("TabWidget", "3x3x3", None))
        self.l_scramble.setText(_translate("TabWidget", "R U\' U D\' D D2 B\' D\' R L\' B2 L2 U D\' F\' R D\' D2 B\' B L B U2 U\' U2 ", None))
        self.l_chronoTime.setText(_translate("TabWidget", "00 : 00 . 000", None))
        item = self.tW_stats1.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Mean", None))
        item = self.tW_stats1.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Average", None))
        item = self.tW_stats1.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Best Time", None))
        item = self.tW_stats1.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Median", None))
        item = self.tW_stats1.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Worst Time", None))
        item = self.tW_stats1.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Standard Deviation", None))
        __sortingEnabled = self.tW_stats1.isSortingEnabled()
        self.tW_stats1.setSortingEnabled(False)
        self.tW_stats1.setSortingEnabled(__sortingEnabled)
        item = self.tW_stats2.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Mean of 3", None))
        item = self.tW_stats2.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Best Mean of 3", None))
        item = self.tW_stats2.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Average of 5", None))
        item = self.tW_stats2.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Best Average of 5", None))
        item = self.tW_stats2.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Average of 12", None))
        item = self.tW_stats2.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Best Average of 12", None))
        self.pB_timeDelete.setText(_translate("TabWidget", "Delete", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_timer), _translate("TabWidget", "Timer", None))
        self.label.setText(_translate("TabWidget", "#          Date                              Time                  Penalty   Scramble", None))
        item = self.tW_histStats1.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Number of solutions", None))
        item = self.tW_histStats1.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Mean", None))
        item = self.tW_histStats1.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Average", None))
        item = self.tW_histStats1.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Standard Deviation", None))
        item = self.tW_histStats1.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Best Time", None))
        item = self.tW_histStats1.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Worst Time", None))
        __sortingEnabled = self.tW_histStats1.isSortingEnabled()
        self.tW_histStats1.setSortingEnabled(False)
        self.tW_histStats1.setSortingEnabled(__sortingEnabled)
        item = self.tW_histStats2.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Mean of 3", None))
        item = self.tW_histStats2.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Mean of 10", None))
        item = self.tW_histStats2.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Mean of 100", None))
        item = self.tW_histStats2.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Mean of 1000", None))
        item = self.tW_histStats2.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Average of 5", None))
        item = self.tW_histStats2.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Average of 12", None))
        __sortingEnabled = self.tW_histStats2.isSortingEnabled()
        self.tW_histStats2.setSortingEnabled(False)
        self.tW_histStats2.setSortingEnabled(__sortingEnabled)
        item = self.tW_histStats3.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Best Mean of 3", None))
        item = self.tW_histStats3.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Best Mean of 10", None))
        item = self.tW_histStats3.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Best Mean of 100", None))
        item = self.tW_histStats3.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Best Mean of 1000", None))
        item = self.tW_histStats3.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Best Average of 5", None))
        item = self.tW_histStats3.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Best Average of 12", None))
        __sortingEnabled = self.tW_histStats3.isSortingEnabled()
        self.tW_histStats3.setSortingEnabled(False)
        self.tW_histStats3.setSortingEnabled(__sortingEnabled)
        TabWidget.setTabText(TabWidget.indexOf(self.tab_history), _translate("TabWidget", "History", None))

from PyKDE4.kdeui import KPlotWidget
