# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cubetimer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName(_fromUtf8("TabWidget"))
        TabWidget.resize(1119, 793)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        TabWidget.setFont(font)
        TabWidget.setAutoFillBackground(False)
        TabWidget.setStyleSheet(_fromUtf8("background-color: rgb(33, 33, 33);"))
        self.tab_timer = QtGui.QWidget()
        self.tab_timer.setObjectName(_fromUtf8("tab_timer"))
        self.tW_stats1 = QtGui.QTableWidget(self.tab_timer)
        self.tW_stats1.setGeometry(QtCore.QRect(170, 440, 241, 180))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 42, 42))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tW_stats1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_stats1.setFont(font)
        self.tW_stats1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_stats1.setAutoFillBackground(False)
        self.tW_stats1.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 10pt \"Sawasdee\";"))
        self.tW_stats1.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_stats1.setFrameShadow(QtGui.QFrame.Plain)
        self.tW_stats1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_stats1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tW_stats1.setAutoScroll(False)
        self.tW_stats1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_stats1.setShowGrid(False)
        self.tW_stats1.setGridStyle(QtCore.Qt.SolidLine)
        self.tW_stats1.setCornerButtonEnabled(False)
        self.tW_stats1.setObjectName(_fromUtf8("tW_stats1"))
        self.tW_stats1.setColumnCount(1)
        self.tW_stats1.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(137, 10, 154))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tW_stats1.setItem(0, 0, item)
        self.tW_stats1.horizontalHeader().setVisible(False)
        self.cB_puzzleType = QtGui.QComboBox(self.tab_timer)
        self.cB_puzzleType.setGeometry(QtCore.QRect(1030, 10, 69, 25))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        self.cB_puzzleType.setFont(font)
        self.cB_puzzleType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cB_puzzleType.setObjectName(_fromUtf8("cB_puzzleType"))
        self.cB_puzzleType.addItem(_fromUtf8(""))
        self.l_scramble = QtGui.QLabel(self.tab_timer)
        self.l_scramble.setGeometry(QtCore.QRect(420, 30, 391, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(20)
        self.l_scramble.setFont(font)
        self.l_scramble.setTextFormat(QtCore.Qt.PlainText)
        self.l_scramble.setObjectName(_fromUtf8("l_scramble"))
        self.tW_stats2 = QtGui.QTableWidget(self.tab_timer)
        self.tW_stats2.setGeometry(QtCore.QRect(450, 440, 251, 180))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tW_stats2.setFont(font)
        self.tW_stats2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tW_stats2.setStyleSheet(_fromUtf8("background-color: rgb(42, 42, 42);\n"
"font: 10pt \"Sawasdee\";"))
        self.tW_stats2.setFrameShape(QtGui.QFrame.NoFrame)
        self.tW_stats2.setAutoScroll(False)
        self.tW_stats2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tW_stats2.setShowGrid(False)
        self.tW_stats2.setObjectName(_fromUtf8("tW_stats2"))
        self.tW_stats2.setColumnCount(1)
        self.tW_stats2.setRowCount(6)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tW_stats2.setHorizontalHeaderItem(0, item)
        self.tW_stats2.horizontalHeader().setVisible(False)
        self.l_chronoTime = QtGui.QLabel(self.tab_timer)
        self.l_chronoTime.setGeometry(QtCore.QRect(170, 150, 791, 231))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(100)
        self.l_chronoTime.setFont(font)
        self.l_chronoTime.setObjectName(_fromUtf8("l_chronoTime"))
        self.lV_times = QtGui.QListView(self.tab_timer)
        self.lV_times.setGeometry(QtCore.QRect(760, 440, 271, 192))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        font.setPointSize(18)
        self.lV_times.setFont(font)
        self.lV_times.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lV_times.setFrameShape(QtGui.QFrame.NoFrame)
        self.lV_times.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lV_times.setAutoScroll(True)
        self.lV_times.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lV_times.setAlternatingRowColors(True)
        self.lV_times.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.lV_times.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerItem)
        self.lV_times.setMovement(QtGui.QListView.Free)
        self.lV_times.setLayoutMode(QtGui.QListView.SinglePass)
        self.lV_times.setViewMode(QtGui.QListView.ListMode)
        self.lV_times.setObjectName(_fromUtf8("lV_times"))
        self.pB_timeDelete = QtGui.QPushButton(self.tab_timer)
        self.pB_timeDelete.setGeometry(QtCore.QRect(930, 650, 88, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sawasdee"))
        self.pB_timeDelete.setFont(font)
        self.pB_timeDelete.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pB_timeDelete.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pB_timeDelete.setObjectName(_fromUtf8("pB_timeDelete"))
        TabWidget.addTab(self.tab_timer, _fromUtf8(""))
        self.tab_history = QtGui.QWidget()
        self.tab_history.setObjectName(_fromUtf8("tab_history"))
        self.keditlistbox_2 = KEditListBox(self.tab_history)
        self.keditlistbox_2.setGeometry(QtCore.QRect(0, 530, 1111, 241))
        self.keditlistbox_2.setObjectName(_fromUtf8("keditlistbox_2"))
        TabWidget.addTab(self.tab_history, _fromUtf8(""))

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)
        TabWidget.setTabOrder(self.cB_puzzleType, self.tW_stats1)

    def retranslateUi(self, TabWidget):
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget", None))
        item = self.tW_stats1.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Mean", None))
        item = self.tW_stats1.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Average", None))
        item = self.tW_stats1.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Best Time", None))
        item = self.tW_stats1.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Median", None))
        item = self.tW_stats1.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Worst Time", None))
        item = self.tW_stats1.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Standard Deviation", None))
        __sortingEnabled = self.tW_stats1.isSortingEnabled()
        self.tW_stats1.setSortingEnabled(False)
        self.tW_stats1.setSortingEnabled(__sortingEnabled)
        self.cB_puzzleType.setItemText(0, _translate("TabWidget", "3x3x3", None))
        self.l_scramble.setText(_translate("TabWidget", "D F2 U F2 R2 D\' B2 U2", None))
        item = self.tW_stats2.verticalHeaderItem(0)
        item.setText(_translate("TabWidget", "Mean of 3", None))
        item = self.tW_stats2.verticalHeaderItem(1)
        item.setText(_translate("TabWidget", "Best Mean of 3", None))
        item = self.tW_stats2.verticalHeaderItem(2)
        item.setText(_translate("TabWidget", "Average of 5", None))
        item = self.tW_stats2.verticalHeaderItem(3)
        item.setText(_translate("TabWidget", "Best Average of 5", None))
        item = self.tW_stats2.verticalHeaderItem(4)
        item.setText(_translate("TabWidget", "Average of 12", None))
        item = self.tW_stats2.verticalHeaderItem(5)
        item.setText(_translate("TabWidget", "Best Average of 12", None))
        self.l_chronoTime.setText(_translate("TabWidget", "00 : 00 . 000", None))
        self.pB_timeDelete.setText(_translate("TabWidget", "Delete", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_timer), _translate("TabWidget", "Timer", None))
        TabWidget.setTabText(TabWidget.indexOf(self.tab_history), _translate("TabWidget", "History", None))

from PyKDE4.kdeui import KEditListBox
